### ISSUE TITLE
Uptime / resources

### ISSUE THREAD

**Issue by pdclark** [lippytak/moodmap#6]
Looks like twilio credits may have run out again?

What kind of (financial) resources do you need to keep the service online?

What kind of (financial/human) resources might be helpful in addressing features or bugs?

**Comment by lippytak** [comment]
Should be back up tonight, sorry about that!

Right now I think it's $50/mo with Twilio + Heroku but I don't mind paying.

JFDI if you're interested. I'll accept PRs. Or if I'm lacking time I'm happy to make you a collaborator on the Twilio/Heroku/Repo. Let me know!
